### ISSUE TITLE
[Idea] Disable Beginner toasts

### ISSUE THREAD

**Issue by Andre601** [DaFuqs/DisableAccessibilityScreen#1]
This could be a bit out of scope for this mod, so perhaps a separate one would be better?

Either way, I suggest to also disable the toast messages displayed whenever you start a fresh made MC instance and join a server/world.
I mean the messages that tell you how to move, to punch a tree, to check the recipe book for recipes (NOT the ones displayed when unlocking recipes), etc.

They are useful for new players, but for ones that play MC long enough are they just annoying and waste time. And sadly is there no option to disable that stuff...

**Comment by DaFuqs** [comment]
TAke a look at the mod "Toast Manager". That should do all of that already. :)
