### ISSUE TITLE
Mark Modrinth release to support 1.19.4

### ISSUE THREAD

**Issue by RoonMoonlight** [DaFuqs/DisableAccessibilityScreen#2]
Hey, I've noticed that this mod supports 1.19.4 release but it only marked 1.19.4-pre1 as supported, can you mark the release setting to support 1.19.4 release?

P.S. For some reason your modrinth page does not have link to the repository, it would be great if you could add link to this repository as well.

**Comment by DaFuqs** [comment]
done
